training_pipeline_config:
  pipeline_name: LoanApproval
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: "https://www.kaggle.com/datasets/ninzaami/loan-predication"
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test 

base_data_ingestion_config:
  raw_data_dir: raw_data
  processed_data_dir: processed_data
  cleaned_data_dir: cleaned_data

base_data_transformation_config:
  resampled_data_dir: resampled_data
  train_resampled_dir: train_resampled
  test_non_resampled_dir: test_non_resampled
  transformed_data_dir: transformed_data

data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  report_file_name: drift_report.json
  report_page_file_name: drift_report.html

data_transformation_config:
  
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.1
  model_config_dir: config
  model_config_file_name: model.yaml

model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models